#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings


# GENERAL SPACE SETTINGS
YABAI -m config layout                       bsp
yabai -m config top_padding                  24 
yabai -m config bottom_padding               16
yabai -m config left_padding                 16
yabai -m config right_padding                16 
yabai -m config window_gap                   16

# rules
## makes system preferences always floating
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Wally$" manage=off
yabai -m rule --add app="^Pulse Secure$" manage=off
yabai -m rule --add app="^Spotify$" manage=off

# signals
## updates workspace widget when space changes
yabai -m signal --add event=space_changed \
  action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"pecan-workspace-jsx\"'"

echo "yabai configuration loaded.."
